name: release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish a new release
    steps:
      - name: Create GitHub release
        uses: arwynfr/actions-conventional-versioning@v3
        with:
          allow-additional-modifiers: true
          feat-upgrades-minor: false
          strict-types: true

      - name: Create version tags
        uses: arwynfr/actions-conventional-versioning/new-versionTags@v3
